### PR TITLE
Added support for mapping DS3 buttons to directions on the analog sticks

### PR DESCRIPTION
**Pull request by StephenCWills**
Currently the ScpMapper.xml interface only supports remapping buttons to other buttons and axes to other axes. This change specifically addresses a use-case where the user may want to map d-pad buttons to analog stick directions by allowing the user to map any button to analog stick directions. I personally came across the need for this feature when playing RPGMaker games with my DS3 controller.

I tried to follow existing conventions when implementing this feature, but I wanted to note the following.

* I tried implementing this a few different ways, and I think I came up with a pretty elegant solution. However, I came to this after only a few hours perusing and playing with the code. I am open to criticism and suggestions.
* I only implemented the mappings for the DS3. I can probably do the same for the DS4, but I don't have a controller to test with.
* Because of the way the XML parsing logic is written, the new &lt;ButtonAnalogDirection&gt; XML section needs to exist in every &lt;DS3&gt; section in the ScpMapper.xml file or else the mapper won't be able to read any mappings. This could potentially break a user's custom profiles during an upgrade if they attempt to use their existing ScpMapper.xml file.

### CODE REVIEW

**Comment by nefarius** [comment]
I appreciate your submission but I will throw out the existing profile manager since it's a nightmare to maintain and too hard to extend. I'll look through the code but it's unlikely that i'll merge it, sorry :(

**Comment by StephenCWills** [comment]
That's fine. My initial intention was to implement a hack for my own personal use, but I figured I'd submit a pull request in case anyone thought it might be useful. Out of curiosity, is there an existing alternative for remapping controller inputs? Also, do you have any plans to provide similar functionality in ScpServer in a more extensible and maintainable way?

**Comment by nefarius** [comment]
Yes, the Project `ScpProfiler` is meant to replace the existing one as a complete re-write. It'll support mapping controller buttons/axes to other buttons/axes, but also to keyboard keys, mouse buttons and movement etc. Currently there's no alternative in the toolkit itself I'm aware of.

**Comment by Daminite** [comment]
I'd love to see integrated direct input too

**Comment by mirhl** [comment]
http://forums.pcsx2.net/Thread-Dinput-Wrapper-for-SCP-Driver
This can remap axis to buttons and viceversa, and does also work with DI

**Comment by Daminite** [comment]
I'm aware of it but it's a little clunky and spikes cpu usage to much to be viable. I'm trying to use it on an old laptop. I removed motion in joy to install this but I'm regretting it a little just because it cost me stable direct input support and sometimes I  get input delay on less used buttons. Integrated directinput with a toggle would help allot. 

Scpserver definatly handles touch pressure better though.

**Comment by mirhl** [comment]
Please, define "stable Direct Input". 
If it's just for triggers and vibrations affair you can try XInput Plus and xkcd drivers (which should replace those of the emulated x360 controller of course)

**Comment by Daminite** [comment]
I just meant that didnt suck the life out of my laptop. When I use dinput wrapper my cpu idles around 50% and I never actually had any issues with motion in joy other than vibration didnt seem to work.

I decided to try this because there doesnt seem to be any development(or website) for mij anymore but now I'm afraid to reinstall it because with my luck this time i'll start getting all the bugs people complain about with it.

**Comment by mirhl** [comment]
No, please. Motionjoy is just a buggy adware. 
As I said, try those alternatives. Vibration should work with both.

**Comment by Daminite** [comment]
Now your just getting condescending. For one thing i've been using better ds3 instead of the default ds3 tool, it eliminates the adware aspect. I was actually happy with mij, it's just dead in the water.

All i was originally asking for was built in direct input support so I didnt have to load 2 other applications that when all 3 are running seem to render my laptop unable to play anything more recent than duke nukem 3d without lag

**Comment by mirhl** [comment]
>  it's just dead in the water

The problem is not **just** being dead. It's dead *and* buggy.
I even got BSOD some times, even with latest version. Did I sound condescending? Well, that was it. 

> All i was originally asking for was built in direct input support so I didnt have to load 2 other applications 

This driver is emulating a xbox 360 driver. DirectInput is emulated just like microsoft meant it to be. 
As I said two times then, you either need [Xinput Plus](https://sites.google.com/site/0dd14lab/xinput-plus) or [xbcd drivers](http://vba-m.com/forum/Thread-xbcd-0-2-7-release-info-updates-will-be-posted-here)

**Pull request closed without merging**
